#!/bin/bash

cp {package.json,yarn.lock,.npmrc} dist

cd dist

yarn install --production

cd ..

cp serverless.layer.yml serverless.yml

yarn deploy --debug

rm -r serverless.yml

cp serverless.sfc.yml serverless.yml

yarn deploy --debug

rm -r serverless.yml
